//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaptopMVCEntities : DbContext
    {
        public LaptopMVCEntities()
            : base("name=LaptopMVCEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_contact> tb_contact { get; set; }
        public virtual DbSet<tb_news> tb_news { get; set; }
        public virtual DbSet<tb_order> tb_order { get; set; }
        public virtual DbSet<tb_orderdetail> tb_orderdetail { get; set; }
        public virtual DbSet<tb_product> tb_product { get; set; }
        public virtual DbSet<tb_productcategory> tb_productcategory { get; set; }
        public virtual DbSet<tb_productImages> tb_productImages { get; set; }
        public virtual DbSet<tb_subscribe> tb_subscribe { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_review> tb_review { get; set; }
    }
}
