//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tb_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_order()
        {
            this.tb_orderdetail = new HashSet<tb_orderdetail>();
        }
    
        public int id { get; set; }
        [DisplayName("Mã đơn hàng")]
        public string code { get; set; }
        [DisplayName("Họ tên khách hàng")]
        [Required(ErrorMessage = "Please enter your fullname")]
        public string customername { get; set; }
        [DisplayName("Số điện thoại")]
        [Required(ErrorMessage = "Please enter your phone")]
        [Phone(ErrorMessage = "Please enter only number"), MaxLength(10)]
        [RegularExpression(@"^0\d{09}$", ErrorMessage = "Phone numbers can only be 10 characters and start with 0 ")]
        public string phone { get; set; }
        [DisplayName("Địa chỉ")]
        [Required(ErrorMessage = "Please enter your address")]
        public string Address { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Please enter your email")]
        [EmailAddress]
        public string email { get; set; }
        [DisplayName("Tổng tiền")]
        public Nullable<decimal> SumMoney { get; set; }
        [DisplayName("Tổng số lượng")]
        public Nullable<int> quantity { get; set; }
        [DisplayName("Trạng thái đơn hàng")]
        public Nullable<int> typeOrder { get; set; }
        [DisplayName("Ngày tạo")]
        public System.DateTime createdate { get; set; }
        [DisplayName("Ngày sửa/cập nhật")]
        public System.DateTime modifieddate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderdetail> tb_orderdetail { get; set; }
    }
}
