//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_orderdetail
    {
        public int id { get; set; }
        public int idorder { get; set; }
        public int idproduct { get; set; }
        public int quantity { get; set; }
    
        public virtual tb_order tb_order { get; set; }
        public virtual tb_product tb_product { get; set; }
    }
}
