//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_product()
        {
            this.tb_orderdetail = new HashSet<tb_orderdetail>();
            this.tb_productImages = new HashSet<tb_productImages>();
            this.tb_review = new HashSet<tb_review>();
        }
    
        public int id { get; set; }
        [DisplayName("Danh mục sản phẩm"), Required(ErrorMessage ="Vui lòng chọn danh mục sản phẩm")]
        public int idProductCategory { get; set; }
        [DisplayName("Tên sản phẩm"), Required(ErrorMessage ="Vui lòng nhập tên sản phẩm")]
        public string title { get; set; }
        [DisplayName("Mô tả sản phẩm"), Required(ErrorMessage ="Vui lòng nhập mô tả sản phẩm")]
        public string description { get; set; }
        [DisplayName("Chi tiết mô tả"), Required(ErrorMessage =" Vui lòng nhập chi tiết mô tả")]
        public string detail { get; set; }
        [DisplayName("CPU"), Required(ErrorMessage ="Vui lòng chọn loại CPU")]
        public string cpu { get; set; }
        [DisplayName("RAM"), Required(ErrorMessage ="Vui lòng chọn loại RAM")]
        public string ram { get; set; }
        [DisplayName("Kích thước màn hình"), Required(ErrorMessage ="Vui lòng chọn kích thước màn hình")]
        public string screen { get; set; }
        [DisplayName("ổ cứng"), Required(ErrorMessage ="Vui lòng chọn dung lượng ổ cứng")]
        public string harddrive { get; set; }
        [DisplayName("Giá gốc"), RegularExpression(@"^\d+$", ErrorMessage ="Vui lòng nhập số")]
        [Required(ErrorMessage ="Vui lòng nhập giá gốc")]
        public decimal price { get; set; }
        [DisplayName("Giá sales"), RegularExpression(@"^\d+$", ErrorMessage = "Vui lòng nhập số")]
        public Nullable<decimal> pricesale { get; set; }
        [DisplayName("Số lượng"), Required(ErrorMessage = "Vui lòng nhập số lượng")]
        [Range(1, int.MaxValue, ErrorMessage ="Số lượng phải lớn hơn 0")]
        public int quantity { get; set; }
        [DisplayName("Sale")]
        public bool isSale { get; set; }
        [DisplayName("Hot")]
        public bool isHot { get; set; }
        [DisplayName("Hiển thị")]
        public bool isActive { get; set; }
        [DisplayName("Lượt xem")]
        public int viewcount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_orderdetail> tb_orderdetail { get; set; }
        public virtual tb_productcategory tb_productcategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_productImages> tb_productImages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_review> tb_review { get; set; }
    }
}
