//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_productImages
    {
        public int id { get; set; }
        [DisplayName("Tên sản phẩm"), Required(ErrorMessage ="Vui lòng chọn sản phẩm")]
        public int idProduct { get; set; }
        [DisplayName("Ảnh sản phẩm")]
        //[Required(ErrorMessage = "Vui lòng chọn ảnh sản phẩm")]
        public string images { get; set; }
        [DisplayName("Ảnh bìa")]
        public bool isDefault { get; set; }
    
        public virtual tb_product tb_product { get; set; }
    }
}
