//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaptopMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    
    public partial class tb_review
    {
        public int id { get; set; }
        [DisplayName("Tên sản phẩm")]
        public int idProduct { get; set; }
        [DisplayName("Họ và tên người đánh giá")]
        public string name { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Thông điệp")]
        public string review { get; set; }
        [DisplayName("Ngày tạo")]
        public System.DateTime createdate { get; set; }
    
        public virtual tb_product tb_product { get; set; }
    }
}
